Use GNUInstallDirs() over setting up LIBDIR manually
Setting LIBDIR manually does not allow overwriting it, and for example
archlinux has /lib64 as a symlink to /lib and hence it's package manager
- pacman - will report an error during installation [1]:

    error: failed to commit transaction (conflicting files)
    cppkafka-git: /usr/lib64 exists in filesystem (owned by filesystem)

  [1]: https://aur.archlinux.org/packages/cppkafka-git/#comment-694919

While with GNUInstallDirs() you can overwrite it like this:
  cmake -DCMAKE_INSTALL_LIBDIR=lib ..